# Generated by Django 5.0.1 on 2024-01-24 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_django", "0003_alter_conversation_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="model_name",
            new_name="gpt_model_name",
        ),
    ]
